spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/CHALLENGE
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver